### PR TITLE
Fix: Raise Error Log when Uplink/Downlink AMBR missing unit

### PR DESCRIPTION
**Pull request by ntut-xuan**
## What's happened?

Hi, I'm Uriah from NYCU Room 215 😄

In this PR, I fix when Uplink/Downlink AMBR in webconsole subscriber page doesn't have unit, it will rasie panic in free5gc SMF.

image

In above image, the Uplink/Downlink AMBR doesn't have unit (Mbps or Kbps), it will make free5gc raise panic in below image.

image

I add error handling in `BitRateTokbps` function and raise Error in `ActivateTunnelAndPDR` function when `BitRateTokbps` function raise the error.

image

## Implmentation

 - [x] Add error handling in `ActivateTunnelAndPDR`

## How to review?

 - Check when Uplink/Downlink AMBR doesn't have unit, it should raise error instead of raw panic.

### CODE REVIEW

**Comment by ianchen0119** [comment]
@ntut-xuan 

Thanks for your PR.
Please help to fix the ci-linter error.

@andy89923 
Please help to review it when you feel free.

**Comment by ntut-xuan** [comment]
> @ntut-xuan
> 
> Thanks for your PR. Please help to fix the ci-linter error.
> 
> @andy89923 Please help to review it when you feel free.

Hi, the lint is fixed, please approve the workflows.

**Comment by andy89923** [comment]
Hi @ntut-xuan,

Thanks for the PR!

Overall it's LGTM, but I think we should add Test for the function under `util`, such as `TestBitRateTokbps` and `TestBitRateTombps`. 

Could you help with the test function? Or I can provide test function and you help with the testcase.

**Comment by ntut-xuan** [comment]
> Hi @ntut-xuan,
> 
> Thanks for the PR!
> 
> Overall it's LGTM, but I think we should add Test for the function under `util`, such as `TestBitRateTokbps` and `TestBitRateTombps`.
> 
> Could you help with the test function? Or I can provide test function and you help with the testcase.

No problem. I'll add it soon.

**Comment by ntut-xuan** [comment]
Hi @ianchen0119 and @andy89923:

I already add the tests and check the implementation passed lint-chcek. 
All testcase follows [AAA pattern](https://medium.com/@pjbgf/title-testing-code-ocd-and-the-aaa-pattern-df453975ab80) and it should show what the testcase check clearly. Please review it, thanks!

**Review by andy89923 — APPROVED** [review]
LGTM! 
@ianchen0119

**Review by ianchen0119 — APPROVED** [review]

**Pull request merged**
